### ISSUE TITLE
Unable to launch GEAP from Ubintu 20.04

### ISSUE THREAD

**Issue by Rohit-Satyam** [nunesijg/rgeap#3]
Hi Developers

I tried installing and launching your tool but all I get is a black screen as shown below:

![image](https://user-images.githubusercontent.com/55479480/179023312-b7bb12a5-ed53-4381-a472-d563719d4723.png)

All the necessary libraries were installed correctly including Mono!! Kindly help!!

All it says is 

```bash
(base) roru:~/GEAP_0.3.0_ubuntu18/GEAP_0.3.0$ ./GEAP.sh 
Initializing GEAP...
```
System Specs
```
SB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by Rohit-Satyam** [comment]
In addition, I am unable to install `rgeap` package. It ends up with the following error:

```r
ileio.cpp: In function ‘bool cleanOpenedStreams()’:
fileio.cpp:351:3: error: ‘_fcloseall’ was not declared in this scope; did you mean ‘fcloseall’?
  351 |   _fcloseall();
      |   ^~~~~~~~~~
      |   fcloseall
fileio.cpp: In function ‘bool readBin2Mem(const Rcpp::String&, int, int, intptr_t)’:
fileio.cpp:336:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  336 |     fread((void*)objPtr, 1, binLen, f);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/usr/lib/R/etc/Makeconf:177: fileio.o] Error 1
ERROR: compilation failed for package ‘rgeap’
* removing ‘/home/roru/R/x86_64-pc-linux-gnu-library/4.2/rgeap’
Error: Failed to install 'rgeap' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpav7dlY/fileba9ce3a0e8f7/rgeap_0.4.0.tar.gz’ had non-zero exit status
```

**Comment by Rohit-Satyam** [comment]
I was able to install it on windows, but now there is new error while loading a project:

![image](https://user-images.githubusercontent.com/55479480/179122003-51a6e74a-c6ab-45d9-86a8-6573bfd806ef.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sum of the columns' FillWeight values cannot exceed 65535.
   at System.Windows.Forms.DataGridView.OnAddingColumn(DataGridViewColumn dataGridViewColumn)
   at System.Windows.Forms.DataGridViewColumnCollection.Add(DataGridViewColumn dataGridViewColumn)
   at GEAP.Classes.Base.Data.InfoMap.RenderToGrid(DataGridView dgv)
   at GEAP.Pages.Analyses.AnalysisOverview.RenderGeoInfo()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at GeapUI.Controls.ButtonForPagesBase.onPageSet() in C:\Users\itama\source\repos\git\GEAP\GeapUI\Controls\ButtonForPages.cs:line 495
   at GeapUI.Controls.ButtonForPagesBase.OnClick(EventArgs e) in C:\Users\itama\source\repos\git\GEAP\GeapUI\Controls\ButtonForPages.cs:line 723
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at GeapUI.Controls.ButtonForPagesBase.OnMouseUp(MouseEventArgs mevent) in C:\Users\itama\source\repos\git\GEAP\GeapUI\Controls\ButtonForPages.cs:line 781
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
GEAP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GeapSDK
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
RGeapAPI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
REnvironment
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
GeapUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
GeapCommon
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
TypeChecker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/TypeChecker.EXE
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Rohit%20Satyam/Pictures/GEAP_0.4.1/GEAP.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nunesijg** [comment]
Hi, @Rohit-Satyam. Thank you for pointing this issue.
**Answering the first and second post**: the main problem is that, when I wrote this article, I had just released a Linux version separately from the Windows version. The problems you pointed are related to bad functioning of both GEAP and _rgeap_, which weren't adapted to Linux in this last version. You can still download the Linux version from the [version history](https://www.inf.ufrgs.br/geap/versions.php) page in our website, but I admit that it's now very dated (it was for version 0.3.0, whereas now we're at 0.4.1).

Unfortunately, GEAP as well as _rgeap_ only works at Windows for now. I apologize for not being able to prioritize the release for Linux, as there wasn't a high demand for it until now and each OS adaptation takes a long time where every feature must be amended and retested with Mono. For now, our recommendation is to use either a Windows machine or a VM to run GEAP until we manage to port to other OSes again.

I'm currently working on a more cross-platform version of GEAP that uses Avalonia instead of Windows Forms. This will also remove the need to use Mono and will enable a more straightforward port to MacOS as well.

**Answering the third post**: Please, tell us which GSE code you used so that I can reproduce your problem. Did you manage to perform the [tutorial in our site](https://www.inf.ufrgs.br/geap/doc.php?page=tuts_quickstart)? The error seems to be a bug in the received columns from _rgeap_ - some columns in the data source may be unnamed, which causes this problem (similarly to [this MSDN post](https://social.msdn.microsoft.com/Forums/windows/en-US/327ff3e0-098c-4657-9af4-20d31fe5d6f0/sum-of-the-columns-fillweight-values-cannot-exceed-65535?forum=winformsdatacontrols)).

**Comment by Rohit-Satyam** [comment]
Hi @nunesijg. Thanks for your reply!! I was using this GSE: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE59099
